### ISSUE TITLE
When Dynamic path and special characters are consecutive, not working

### ISSUE THREAD

**Issue by matamatanot** [aspida/aspida#605]
## Description

If the dynamic path and the special character string are consecutive, the output will not be correct.

e.g.
The `_userId@string` works fine. The others do not work correctly.

- `users`
  -  `_userId@string`
     - index.ts
  -  `_userId@string%3Aedit`
     - index.ts
  -  `_userId@string%3Adelete`
     - index.ts

## Environment

- **Package version:**
  
  `v1.1.1`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v14.13.1`
- **npm version:**
  
  `v6.14.8`

**Comment by matamatanot** [comment]
On another note, I feel like I want to treat [:(%3A)] the same way aspida treat [/].

e.g.

- users
  - `_userId@string`
     - `index.ts`
     - `%3Aedit`
       - `index.ts`
     - `%3Adelete`
       - `index.ts`

**Or**

- users
  - `_userId@string`
     - `index.ts`
     - `edit` (add option)
       - `index.ts`
     - `delete` (add option)
       - `index.ts`

It is no longer necessary to write `_userId@string` multiple times. How to tell aspida whether to use [:] or [/] is a difficult problem.

**Comment by solufa** [comment]
@matamatanot 

Please update.
A fixed string can be given after the path variable.
https://github.com/aspida/aspida/#define-endpoints-that-contain-special-characters

But I couldn't split the directory for an additional string.
Because I couldn't adopt a complex implementation for a feature that was not in high demand.
